pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    resuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    go test -v ./...
                }
            }
        }
    }
}
